blank_issues_enabled: false
contact_links:
  - name: Report a bug
    url: https://github.com/tox-dev/toml-fmt/issues/new?template=tox-toml-fmt-bug.yml
    about: Report bugs in the main repository
  - name: Request a feature
    url: https://github.com/tox-dev/toml-fmt/issues/new?template=tox-toml-fmt-feature.yml
    about: Suggest enhancements in the main repository
